FROM python:3.9-slim

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy only needed code
COPY api ./api
COPY feature_store ./feature_store
COPY mlruns ./mlruns
COPY utils ./utils

ENV MLFLOW_TRACKING_URI=file:/app/mlruns

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
